# Generated by Django 3.1.3 on 2020-11-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
