# Generated by Django 3.1.3 on 2020-12-02 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201109_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('index', models.PositiveSmallIntegerField()),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('camera', models.JSONField()),
                ('interactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='products.interactive')),
            ],
        ),
    ]
