# Generated by Django 3.1.3 on 2020-12-02 03:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_annotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['index']},
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='camera',
        ),
        migrations.AddField(
            model_name='annotation',
            name='camPosition',
            field=models.CharField(default='0 0 0', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,(-)?\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
