# Generated by Django 3.1.3 on 2020-12-02 17:45

from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201202_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='camPosition',
            field=products.models.CommaSeparatedFloatField(default='5,5,5', max_length=50),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='position',
            field=products.models.CommaSeparatedFloatField(default='0,0,0', max_length=50),
        ),
    ]
