# Generated by Django 3.1.3 on 2020-12-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201202_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='camPosition',
            new_name='cam_position',
        ),
    ]
