# Generated by Django 3.1.3 on 2020-12-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201202_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='has_label',
            field=models.BooleanField(default=True),
        ),
    ]
