# Generated by Django 3.1.3 on 2020-12-17 04:18

from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201217_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='polar_limits',
            field=products.models.CommaSeparatedFloatField(default='0, 180', max_length=20),
        ),
    ]
